# Generated by Django 3.0.4 on 2020-03-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200329_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
