# Generated by Django 3.0.4 on 2020-04-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200409_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='users',
            new_name='user',
        ),
    ]
