# Generated by Django 3.0.4 on 2020-04-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200409_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profil_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
