# Generated by Django 3.0.4 on 2020-04-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customer_profil_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profil_pic',
            new_name='profile_pic',
        ),
    ]
